//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FormationEFEntities : DbContext
    {
        public FormationEFEntities()
            : base("name=FormationEFEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author> Authors1 { get; set; }
        public DbSet<Card> Cards1 { get; set; }
        public DbSet<Media> Media { get; set; }
        public DbSet<Page> Pages1 { get; set; }
        public DbSet<Publisher> Publishers1 { get; set; }
    }
}
