//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        public Media()
        {
            this.pages = new HashSet<Page>();
            this.authors = new HashSet<Author>();
            this.cards = new HashSet<Card>();
        }
    
        public int id { get; set; }
        public string Title { get; set; }
        public float price { get; set; }
        public Nullable<int> numISBN { get; set; }
        public Nullable<int> nbPages { get; set; }
        public Nullable<int> nbTracks { get; set; }
        public Nullable<int> category { get; set; }
        public Nullable<System.DateTime> dateParution { get; set; }
        public string langue { get; set; }
        public Nullable<int> id_Publisher { get; set; }
    
        public virtual Publisher publisher { get; set; }
        public virtual ICollection<Page> pages { get; set; }
        public virtual ICollection<Author> authors { get; set; }
        public virtual ICollection<Card> cards { get; set; }
    }
}
